import {Question} from '../types'
import {v4 as uuidv4} from 'uuid'

// Beispielfragen für die App
export const sampleQuestions: Question[] = [
    {
        id: uuidv4(),
        question: 'Welches Land hat die größte Fläche?',
        options: ['Russland', 'Kanada', 'China', 'USA'],
        correctAnswer: 0,
        category: 'Geografie',
        difficulty: 'easy',
    },
    {
        id: uuidv4(),
        question: 'Wie viele Planeten hat unser Sonnensystem?',
        options: ['7', '8', '9', '10'],
        correctAnswer: 1,
        category: 'Astronomie',
        difficulty: 'easy',
    },
    {
        id: uuidv4(),
        question: 'Wer schrieb "Romeo und Julia"?',
        options: ['Charles Dickens', 'Mark Twain', 'William Shakespeare', 'Friedrich Schiller'],
        correctAnswer: 2,
        category: 'Literatur',
        difficulty: 'easy',
    },
    {
        id: uuidv4(),
        question: 'Welches Element hat die chemische Abkürzung "O"?',
        options: ['Osmium', 'Sauerstoff', 'Gold', 'Silber'],
        correctAnswer: 1,
        category: 'Wissenschaft',
        difficulty: 'easy',
    },
    {
        id: uuidv4(),
        question: 'Welche Sprache wird in Brasilien hauptsächlich gesprochen?',
        options: ['Spanisch', 'Englisch', 'Französisch', 'Portugiesisch'],
        correctAnswer: 3,
        category: 'Geografie',
        difficulty: 'medium',
    },
    {
        id: uuidv4(),
        question: 'Welches Jahr markiert den Beginn des Ersten Weltkriegs?',
        options: ['1914', '1916', '1918', '1920'],
        correctAnswer: 0,
        category: 'Geschichte',
        difficulty: 'medium',
    },
    {
        id: uuidv4(),
        question: 'Welcher Planet ist der Sonne am nächsten?',
        options: ['Venus', 'Merkur', 'Mars', 'Erde'],
        correctAnswer: 1,
        category: 'Astronomie',
        difficulty: 'medium',
    },
    {
        id: uuidv4(),
        question: 'Was ist die Hauptstadt von Australien?',
        options: ['Sydney', 'Melbourne', 'Canberra', 'Perth'],
        correctAnswer: 2,
        category: 'Geografie',
        difficulty: 'medium',
    },
    {
        id: uuidv4(),
        question: 'Welches dieser Tiere ist kein Säugetier?',
        options: ['Delfin', 'Fledermaus', 'Wal', 'Pinguin'],
        correctAnswer: 3,
        category: 'Biologie',
        difficulty: 'medium',
    },
    {
        id: uuidv4(),
        question: 'Welches ist das am häufigsten vorkommende chemische Element im Universum?',
        options: ['Wasserstoff', 'Helium', 'Sauerstoff', 'Stickstoff'],
        correctAnswer: 0,
        category: 'Wissenschaft',
        difficulty: 'hard',
    },
    {
        id: uuidv4(),
        question: 'Wer komponierte die "Mondscheinsonate"?',
        options: ['Wolfgang Amadeus Mozart', 'Johann Sebastian Bach', 'Ludwig van Beethoven', 'Franz Schubert'],
        correctAnswer: 2,
        category: 'Musik',
        difficulty: 'hard',
    },
    {
        id: uuidv4(),
        question: 'Welche dieser Galaxien ist die Milchstraße am nächsten?',
        options: ['Andromeda-Galaxie', 'Dreiecksgalaxie', 'Whirlpool-Galaxie', 'Sombrerogalaxie'],
        correctAnswer: 0,
        category: 'Astronomie',
        difficulty: 'hard',
    },
    {
        id: uuidv4(),
        question: 'In welchem Jahr wurde die Allgemeine Relativitätstheorie von Albert Einstein veröffentlicht?',
        options: ['1905', '1915', '1925', '1935'],
        correctAnswer: 1,
        category: 'Wissenschaft',
        difficulty: 'hard',
    },
    {
        id: uuidv4(),
        question: 'Welches ist das längste Wort in der deutschen Sprache laut Duden?',
        options: [
            'Donaudampfschifffahrtsgesellschaftskapitän',
            'Kraftfahrzeughaftpflichtversicherung',
            'Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz',
            'Grundstücksverkehrsgenehmigungszuständigkeitsübertragungsverordnung'
        ],
        correctAnswer: 3,
        category: 'Sprache',
        difficulty: 'hard',
    },
    {
        id: uuidv4(),
        question: 'Welches Land hat die höchste Bevölkerungsdichte?',
        options: ['Indien', 'Singapur', 'Monaco', 'Bangladesch'],
        correctAnswer: 2,
        category: 'Geografie',
        difficulty: 'hard',
    },
]